import React from "react";
import { TOKENS } from "@platform/ui";

// docs/specs/third-party-api-origin-tagging.md — the API response shape
// resolve-origin-display.ts (apps/api/src/lib) produces, attached as
// `origin` on ticket/comment/activity-timeline responses. Null means
// normal, human, in-app creation — no tag rendered (spec §V).
export type Origin =
  | {
      mechanism: "api" | "handoff";
      appName: string;
      performerUserId: string;
    }
  | null
  | undefined;

const LABEL_BY_MECHANISM: Record<"api" | "handoff", string> = {
  api: "External",
  handoff: "Redirected",
};

/**
 * Renders `External · [App] · [Person]` / `Redirected · [App] · [Person]`
 * per docs/specs/third-party-api-origin-tagging.md R1–R5. Returns null
 * (renders nothing) when origin is null/undefined — a normal, in-app
 * ticket/comment/timeline entry never carries a tag.
 */
export function OriginTag({
  origin,
  size = "normal",
}: {
  origin: Origin;
  size?: "normal" | "compact";
}): React.ReactElement | null {
  if (!origin) return null;

  const fontSize = size === "compact" ? "10.5px" : "11.5px";
  const padding = size === "compact" ? "1px 6px" : "2px 8px";

  return (
    <span
      title={`Created via ${origin.appName} by ${origin.performerUserId}`}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "4px",
        padding,
        borderRadius: "999px",
        fontSize,
        fontWeight: 600,
        lineHeight: 1.4,
        whiteSpace: "nowrap",
        background: "var(--bg-secondary)",
        border: `1px solid var(--border-primary)`,
        color: "var(--text-tertiary)",
      }}
    >
      <span style={{ color: "var(--accent-primary)" }}>
        {LABEL_BY_MECHANISM[origin.mechanism]}
      </span>
      <span aria-hidden="true">·</span>
      <span
        style={{
          maxWidth: "140px",
          overflow: "hidden",
          textOverflow: "ellipsis",
        }}
      >
        {origin.appName}
      </span>
      <span aria-hidden="true">·</span>
      <span
        style={{
          maxWidth: "120px",
          overflow: "hidden",
          textOverflow: "ellipsis",
        }}
      >
        {origin.performerUserId}
      </span>
    </span>
  );
}

/**
 * Ticket-detail banner variant (R1/R2) — "Auto-generated by [App] via
 * [Person]" styling, more prominent than the inline list/comment badge.
 */
export function OriginBanner({
  origin,
}: {
  origin: Origin;
}): React.ReactElement | null {
  if (!origin) return null;

  const label = origin.mechanism === "api" ? "External" : "Redirected";

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "8px",
        padding: "8px 12px",
        borderRadius: TOKENS.radiusSm,
        background: "var(--bg-secondary)",
        border: "1px solid var(--border-primary)",
        fontSize: "12.5px",
        color: "var(--text-secondary)",
        marginBottom: "12px",
      }}
    >
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
        style={{ flexShrink: 0, color: "var(--accent-primary)" }}
      >
        <rect x="4" y="4" width="16" height="16" rx="2" />
        <path d="M9 9h6v6H9z" />
      </svg>
      <span>
        <strong style={{ color: "var(--text-primary)" }}>{label}</strong> ·
        Created via <strong>{origin.appName}</strong> by{" "}
        <strong>{origin.performerUserId}</strong>
      </span>
    </div>
  );
}
